---
- block:
  - name: Check for version
    set_fact:
      error_string: "{{ ansible_distribution }} {{ ansible_distribution_version }} is not supported in dpdk mode"
  - include: error.yml
  when:  (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.4.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.3.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.2.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.1.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.0.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.5.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.6.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.7.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.8.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('7.9.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('8.1.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('8.2.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('8.3.*'))) and
         (not (ansible_distribution == 'CentOS' and ansible_distribution_version is match('8.4.*'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('8.4'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('8.3'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('8.2'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('8.1'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.9'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.8'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.7'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.6'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.5'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.4'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.3'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.2'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.1'))) and
         (not (ansible_distribution == 'OracleLinux' and ansible_distribution_version is match('7.0'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('8.4'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('8.3'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('8.2'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('8.1'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.9'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.8'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.7'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.6'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.5'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.4'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.3'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.2'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.1'))) and
         (not (ansible_distribution == 'RedHat' and ansible_distribution_version is match('7.0'))) and
         (not (ansible_distribution == 'Ubuntu' and ansible_distribution_version is match('20.04'))) and
         (not (ansible_distribution == 'Ubuntu' and ansible_distribution_version is match('18.04'))) and
         (not (ansible_distribution == 'Ubuntu' and ansible_distribution_version is match('16.04')))

- name: Avi SE | Perform specific os tasks
  include: os/{{ ansible_distribution|lower }}.yml

- name: Configure DPDK Pre Parameters
  set_fact:
    se_dpdk_pre: >
      modprobe uio;
      mkdir -p /mnt/huge; umount /mnt/huge; rm /mnt/huge/*; mount -t hugetlbfs nodev /mnt/huge

- name: Configure DPDK Post Parameters
  set_fact:
    se_dpdk_post: >
      rmmod igb_uio;
      rmmod rte_kni; umount /mnt/huge
