---
# This task will appropriately start the actions on SE's
- name: Check SeGroup Upgrade in progress
  fail:
    msg: SeGroup upgrade in progress
  when: (se_action == "start") and (ups is defined) and ups

- include: version_check.yml
  when: se_action != "verify"

- name: Avi SE actions
  include: "se_{{ se_action }}.yml"
